1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [1]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(arr)

# Interchange rows and columns (Transpose)
transposed_arr = arr.T
print("\nTransposed Array:")
print(transposed_arr)


Original Array:
[[51 35 87]
 [27 66 39]
 [31 16 79]]

Transposed Array:
[[51 27 31]
 [35 66 16]
 [87 39 79]]


2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [2]:
import numpy as np

# Generate a 1D array with 10 elements
arr = np.arange(10)
print("Original 1D Array:")
print(arr)

# Reshape into a 2x5 array
arr_2x5 = arr.reshape(2, 5)
print("\nReshaped into 2x5 Array:")
print(arr_2x5)

# Reshape into a 5x2 array
arr_5x2 = arr.reshape(5, 2)
print("\nReshaped into 5x2 Array:")
print(arr_5x2)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped into 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [3]:
import numpy as np

# Create a 4x4 array with random float values
arr = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(arr)

# Add a border of zeros around the array
bordered_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with a Border of Zeros:")
print(bordered_arr)


Original 4x4 Array:
[[0.53150626 0.89128508 0.03853383 0.92029095]
 [0.80510901 0.83689851 0.17288873 0.85731589]
 [0.85932244 0.05698543 0.43244141 0.56581399]
 [0.60318143 0.97233298 0.24102208 0.061473  ]]

6x6 Array with a Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.53150626 0.89128508 0.03853383 0.92029095 0.        ]
 [0.         0.80510901 0.83689851 0.17288873 0.85731589 0.        ]
 [0.         0.85932244 0.05698543 0.43244141 0.56581399 0.        ]
 [0.         0.60318143 0.97233298 0.24102208 0.061473   0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5

In [4]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
arr = np.arange(10, 61, 5)
print(arr)


[10 15 20 25 30 35 40 45 50 55 60]


5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element

In [5]:
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_arr = np.char.upper(arr)
lowercase_arr = np.char.lower(arr)
titlecase_arr = np.char.title(arr)
capitalize_arr = np.char.capitalize(arr)

# Display the results
print("Original Array:")
print(arr)

print("\nUppercase Transformation:")
print(uppercase_arr)

print("\nLowercase Transformation:")
print(lowercase_arr)

print("\nTitle Case Transformation:")
print(titlecase_arr)

print("\nCapitalize Transformation:")
print(capitalize_arr)


Original Array:
['python' 'numpy' 'pandas']

Uppercase Transformation:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Transformation:
['python' 'numpy' 'pandas']

Title Case Transformation:
['Python' 'Numpy' 'Pandas']

Capitalize Transformation:
['Python' 'Numpy' 'Pandas']


6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [6]:
import numpy as np

# Create a NumPy array of words
words = np.array(['hello', 'numpy', 'array'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words)

# Display the results
print("Original Array of Words:")
print(words)

print("\nArray with Spaces Between Characters:")
for word in spaced_words:
    print(word)


Original Array of Words:
['hello' 'numpy' 'array']

Array with Spaces Between Characters:
h e l l o
n u m p y
a r r a y


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [7]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Perform element-wise addition
addition = array1 + array2
print("Element-wise Addition:")
print(addition)

# Perform element-wise subtraction
subtraction = array1 - array2
print("\nElement-wise Subtraction:")
print(subtraction)

# Perform element-wise multiplication
multiplication = array1 * array2
print("\nElement-wise Multiplication:")
print(multiplication)

# Perform element-wise division
division = array1 / array2
print("\nElement-wise Division:")
print(division)


Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [8]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [9]:
import numpy as np

# Generate an array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)
print("Random Integers Array:")
print(random_integers)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find and display all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]
print("\nPrime Numbers in the Array:")
print(prime_numbers)


Random Integers Array:
[573 967 476  83 781 583  48  69 275 674 734 272  95 592 879 587 538 115
 132 205 628 944 594 597 610 478 399 226 250 709 690 238 441 414 191 807
 443 218 679 196 983 119 212  62 648  34 770 935 978 364 641 791 949 767
 121 597 689 559 501  92 161 141 977 805 290 794 143 576 150 495 316 488
 255 228 661 924 636 476 351 947 372 963 274 843 853 429 642 763 426 573
 720  22 194 367 756 316 772 559 511 733]

Prime Numbers in the Array:
[967, 83, 587, 709, 191, 443, 983, 641, 977, 661, 947, 853, 367, 733]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages

In [11]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# Here we simulate temperatures between 20 and 35 degrees Celsius
daily_temperatures = np.random.uniform(20, 35, size=30)
print("Daily Temperatures for a Month:")
print(daily_temperatures)

# Calculate the weekly averages
# Reshape the array to have 4 weeks (considering 30 days)
weekly_averages = daily_temperatures.reshape(5,6).mean(axis=1)

# Display the weekly averages
print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures for a Month:
[20.01997059 28.15320613 28.71725828 26.0740004  23.56625334 24.17572515
 24.30874247 31.94993106 29.58995756 34.97499993 29.83970635 32.55727661
 25.10020825 33.29585385 25.14679835 21.38322965 27.11062531 28.15128707
 34.11984191 26.30390217 25.87684242 30.01280915 24.14462794 28.50235684
 25.32172568 29.3516577  24.28566517 28.61812306 20.72724267 30.53988766]

Weekly Averages:
[25.11773565 30.536769   26.69800041 28.16006341 26.47405032]
